name: Publish images

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: [14, 15, 16, 17]
        os: ["bookworm", "bullseye"]
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: extractions/setup-just@v2

      - name: Build Docker image
        run: |
          just build ${{ matrix.version }} ${{ matrix.os }}

      - name: Publish Docker image
        run: |
          just publish ${{ matrix.version }} ${{ matrix.os }}
