# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Security scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '37 15 * * 3'

permissions:
  contents: read

jobs:
  Security:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Security scan Postgre Container
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        version: [14, 15, 16]
        os: ["bookworm"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: extractions/setup-just@v1

      - name: Build Docker image
        run: |
          just build ${{ matrix.version }} ${{ matrix.os }}
          just publish ${{ matrix.version }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/bitbytelabio/postgres:${{ matrix.version }}'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
